services:
  - type: web
    name: bot-citas-homologacion
    env: python
    region: frankfurt
    plan: standard
    buildCommand: "./build.sh"
    startCommand: "python main.py"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ADMIN_USER_ID
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: bot-citas-db
          property: connectionString
    healthCheckPath: /health

databases:
  - name: bot-citas-db
    databaseName: citasbot
    plan: starter
